version: "3.8"

services:
  # PostgreSQL Database
  postgres-db:
    image: postgres:14-alpine
    container_name: shop-postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shop-network
    restart: unless-stopped

  # Spring Boot Backend
  shop-backend:
    build:
      context: ../shop
      dockerfile: ../docker-config/backend.dockerfile
    container_name: shop-backend
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    networks:
      - shop-network
    restart: unless-stopped

  # Angular Frontend with Nginx
  shop-frontend:
    build:
      context: ../online-shop
      dockerfile: ../docker-config/frontend.dockerfile
    container_name: shop-frontend
    depends_on:
      - shop-backend
    ports:
      - "80:80"
    networks:
      - shop-network
    restart: unless-stopped

networks:
  shop-network:
    driver: bridge

volumes:
  postgres-data:
